version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # React app port
    depends_on:
      - backend  # Ensure backend starts first
    environment:
      - REACT_APP_BACKEND_URL=https://curly-space-umbrella-wrvpgg974x9j25x4r-3001.app.github.dev/  # Point frontend to the backend service
      - REACT_APP_API_URL=https://curly-space-umbrella-wrvpgg974x9j25x4r-3000.app.github.dev/  # Point to API
      - REACT_APP_DB_URL=https://curly-space-umbrella-wrvpgg974x9j25x4r-3306.app.github.dev/  # Point to MySQL
    volumes:
      - ./frontend:/app  # Mount frontend folder for live reload
      - /app/node_modules  # Avoid overwriting node_modules
    command: ["npm", "start"]  # React dev server with hot-reloading

  backend:
    build: ./backend
    ports:
      - "3001:3001"  # Backend service port
    depends_on:
      - db  # Ensure MySQL starts first
    environment:
      - DATABASE_HOST=db  # Refer to MySQL service as 'db'
      - DATABASE_USER=root
      - DATABASE_PASSWORD=your_new_password
      - DATABASE_NAME=user_dashboard
      - BACKEND_URL=https://curly-space-umbrella-wrvpgg974x9j25x4r-3001.app.github.dev/  # Backend URL
      - DB_URL=https://curly-space-umbrella-wrvpgg974x9j25x4r-3306.app.github.dev/  # MySQL URL
    volumes:
      - ./backend:/app  # Mount backend folder for live reload
      - /app/node_modules  # Avoid overwriting node_modules
    command: ["npm", "run", "dev"]  # Use nodemon or equivalent for backend dev server

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_new_password
      MYSQL_DATABASE: user_dashboard  # Initialize with your database
    ports:
      - "3306:3306"  # MySQL default port
    volumes:
      - db_data:/var/lib/mysql  # Persist database data
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -pyour_new_password"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
