apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  labels:
    app: nodeapp
spec:
  type: LoadBalancer  # Changed from NodePort to LoadBalancer
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80          # Exposing port 80
      targetPort: 3000  # Targeting container port 3000
